spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jooq.JooqAutoConfiguration
  #DataBase
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/holliverse}
    username: ${DB_USER_CUSTOMER:postgres}
    password: ${DB_PASS_CUSTOMER:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:20}
      minimum-idle: ${DB_POOL_MIN:5}
      connection-timeout: 3000
      validation-timeout: 1000

  flyway:
    user: ${FLYWAY_USER:${spring.datasource.username}}
    password: ${FLYWAY_PASSWORD:${spring.datasource.password}}

server:
  port: ${SERVER_PORT:8080}

app:
  runtime: customer
