spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jooq.JooqAutoConfiguration

  flyway:
    user: ${DB_USER_MIGRATOR:db_migrator}
    password: ${DB_PASS_MIGRATOR:db_migrator_pw}

server:
  port: ${SERVER_PORT:8080}

app:
  runtime: customer
  jwt:
    secret: ${JWT_SECRET:change-this-secret-key-at-least-32-characters}
    access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:604800000}
    refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:1209600000}
