name: pr-verification

on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened, edited]

jobs:
  commit-policy:
    uses: one-year-gap/infra/.github/workflows/commit-policy.yml@main
    
