name: test-coverage

on:
  pull_request:
#
permissions:
  contents: read
  pull-requests: write

jobs:
  coverage:
    uses: one-year-gap/infra/.github/workflows/test-coverage.yml@main
    with:
      working-directory: .
      min-line-overall: 0.1
      min-branch-overall: 0.1
      min-line-changed: 0.1
      min-branch-changed: 0.1
